version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.1-browsers
      - image: circleci/mysql:latest
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
       

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: Build real-affinities and run tests
          command: php -version
      - run:
          name: Build real-affinities and run tests
          command: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
      - run:
          name: get nodejs
          command: sudo apt-get install -y nodejs
      - run:
          name: mocha
          command: sudo npm install --global mocha
